services:
  backend:
    build:
      context: .
      dockerfile: devbackDockerfile
    environment:
      - KAKAO_LOGIN_RESTAPI_KEY
      - KAKAO_LOGIN_CLIENT_SECRET
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - MYSQL_URL
      - MYSQL_HOST
      - MYSQL_DATABASE
      - JWT_SECRET_KEY
      - KAKAO_LOGIN_REDIRECT_URI
      - KAKAO_TOKEN_RESPONSE_URI
      - KAKAO_LOCAL_TOKEN_RESPONSE_URI
      - KAKAO_LOCAL_TOKEN
      - COOKIE_DOMAIN
      - REDIS_HOSTNAME
      - REDIS_PORT
      - OPENAI_MODEL
      - OPENAI_SECRET_KEY
      - TZ=Asia/Seoul
    networks:
      - night-letter

  frontend:
    build:
      context: .
      dockerfile: devfrontDockerfile
    environment:
      - NEXT_PUBLIC_MODE
      - NEXT_PUBLIC_URL
      - NEXT_PUBLIC_API_URL
      - TZ=Asia/Seoul
    networks:
      - night-letter

networks:
  night-letter:
    driver: bridge
    external: true
